version: '3.8'

services:
  db:
    image: postgres:15
    container_name: scheduling_db
    restart: always
    environment:
      - POSTGRES_USER=scheduler_user
      - POSTGRES_PASSWORD=scheduler_pass
      - POSTGRES_DB=scheduling_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_scheduler
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
